/**
 * context-overflow 溢出恢复回归测试（官方 agent/request-error 机制，对齐 compaction-basic）。
 *
 * 场景：模型请求返回 400 exceed_context_size_error（稳定错误码 CONTEXT_WINDOW_EXCEEDED，
 * 不写死 token 数）→ ARGP 钩子捕获 → compactIfNeeded(agent, 'context-overflow') 强制剪枝
 * → surface 换代 → 返回 { kind: 'retry' } 让 agent loop 重发请求。
 *
 * 断言：
 *  1) 溢出错误 → 剪枝发生（replaceGeneration 推进 + records 记录）+ 返回 retry
 *  2) 非溢出错误码 → 不剪枝、不 retry（保留原始错误）
 *  3) maxOverflowRetries 上限 → 第二次溢出不再 retry
 *  4) context-overflow trigger 跳过 pressure 门槛（估算 < threshold 也强制剪；
 *     'pressure' trigger 同一会话返回 null）
 */
import test from 'node:test'
import assert from 'node:assert/strict'
import { Context } from '@deepseek-ai/cordis'
import { mountAgentLoopTestDependencies } from '@deepseek-ai/dsh-agent-loop-testkit'
import { CONTEXT_WINDOW_EXCEEDED_CODE, createUserMessage, type LlmFailure } from '@deepseek-ai/dsh-llm'
import { Session, SessionId } from '@deepseek-ai/dsh-session'
import { agentEvents, type Agent } from '@deepseek-ai/dsh-agent'
import { ArgpGraphEngine } from '../src/argp-graph-engine.ts'

async function makeEngine(config: Record<string, unknown> = {}): Promise<{ ctx: Context; engine: ArgpGraphEngine }> {
  const ctx = new Context()
  await mountAgentLoopTestDependencies(ctx, { systemPrompt: { persona: 'argp context-overflow test' } })
  await ctx.plugin(ArgpGraphEngine, { windowTokens: 100, retainTokens: 50, minSpanChars: 20, recencyGuard: 0, maxPasses: 16, ...config })
  return { ctx, engine: ctx.compaction as ArgpGraphEngine }
}

function appendUser(session: Session, text: string, turn: number): void {
  // turn 必须作为事件 data 一级字段（atomize 读 data.turn 计算 latestTurn / 闭包保护窗口）
  session.append('user/message', {
    turn,
    ...createUserMessage({ content: [{ type: 'text', text }], source: { kind: 'user' } }),
  } as never, { surfaceOp: 'append' })
}

/** 多轮 user 消息，总量远高于 retain 目标（可剪）。 */
function buildBigSession(): Session {
  const session = Session.create(SessionId('overflow-big'))
  for (let turn = 1; turn <= 6; turn += 1) {
    appendUser(session, 'u' + turn + ': ' + 'x'.repeat(120), turn)
  }
  return session
}

/** 多轮 user 消息，估算 token < threshold（pressure 会跳过，context-overflow 不跳）。 */
function buildSmallSession(): Session {
  const session = Session.create(SessionId('overflow-small'))
  for (let turn = 1; turn <= 5; turn += 1) {
    appendUser(session, 's' + turn + ': ' + 'y'.repeat(40), turn)
  }
  return session
}

function stubAgent(session: Session): Agent {
  return { session, options: {} } as Agent
}

function overflowFailure(message = 'request (197482 tokens) exceeds the available context size (196608 tokens)'): LlmFailure {
  return { message, code: CONTEXT_WINDOW_EXCEEDED_CODE }
}

/** 触发一次 agent/request-error 事件（cordis waterfall），返回决策 action。 */
function emitRequestError(
  ctx: Context,
  agent: Agent,
  failure: LlmFailure,
): Promise<{ kind: 'retry' } | undefined> {
  const turn = agent.session.events.findLast(event => event.type === 'turn/start')?.data.turn ?? 1
  return agentEvents(ctx, agent).waterfall(
    'agent/request-error',
    { turn, step: 1, provider: 'test', failure, retryPolicy: undefined, signal: new AbortController().signal },
    () => Promise.resolve(undefined),
  )
}

test('溢出 400 → 强制剪枝 + 返回 retry（surface 换代）', async () => {
  const { ctx, engine } = await makeEngine()
  try {
    const session = buildBigSession()
    engine.setSession(session)
    const agent = stubAgent(session)
    const generationBefore = session.surface.replaceGeneration
    const action = await emitRequestError(ctx, agent, overflowFailure())
    assert.equal(action?.kind, 'retry', 'overflow must produce a retry decision')
    assert.ok(session.surface.replaceGeneration > generationBefore, 'surface must be regenerated by the prune')
    assert.ok(engine.records.length >= 1, 'a prune transaction must be recorded')
    const record = engine.records[0]
    assert.ok(record !== undefined && record.shadowedSeqs.length > 0, 'prune must shadow nodes')
  } finally {
    await ctx.fiber.dispose()
  }
})

test('非溢出错误码 → 不剪枝、不 retry（保留原始错误）', async () => {
  const { ctx, engine } = await makeEngine()
  try {
    const session = buildBigSession()
    engine.setSession(session)
    const agent = stubAgent(session)
    const generationBefore = session.surface.replaceGeneration
    const action = await emitRequestError(ctx, agent, { message: 'rate limited', code: 'RATE_LIMITED' })
    assert.equal(action, undefined, 'non-overflow errors must not retry')
    assert.equal(session.surface.replaceGeneration, generationBefore, 'no prune must happen')
    assert.equal(engine.records.length, 0)
  } finally {
    await ctx.fiber.dispose()
  }
})

test('maxOverflowRetries 上限：第二次溢出不再 retry', async () => {
  const { ctx, engine } = await makeEngine({ maxOverflowRetries: 1 })
  try {
    const session = buildBigSession()
    engine.setSession(session)
    const agent = stubAgent(session)
    // 第一次：剪枝 → retry
    const first = await emitRequestError(ctx, agent, overflowFailure())
    assert.equal(first?.kind, 'retry')
    // 第二次（同一 agent）：已达重试上限 → 保留错误，不 retry
    const second = await emitRequestError(ctx, agent, overflowFailure())
    assert.equal(second, undefined, 'second overflow must respect the retry cap')
  } finally {
    await ctx.fiber.dispose()
  }
})

test('context-overflow trigger 跳过 pressure 门槛（估算低于触发线也强制剪）', async () => {
  const { ctx, engine } = await makeEngine()
  try {
    const session = buildSmallSession()
    engine.setSession(session)
    // pressure：估算 < threshold → 跳过
    const pressureResult = await engine.compactIfNeeded({ session } as never, 'pressure', new AbortController().signal)
    assert.equal(pressureResult, null, 'below-threshold estimate must skip under pressure trigger')
    // context-overflow：无视门槛强制剪
    const overflowResult = await engine.compactIfNeeded({ session } as never, 'context-overflow', new AbortController().signal)
    assert.ok(overflowResult !== null, 'context-overflow must prune even below the pressure threshold')
    assert.ok(engine.records.length >= 1)
  } finally {
    await ctx.fiber.dispose()
  }
})
